spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=echangeaf;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin123
  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      ddl-auto: update
